
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch (adjust as needed)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js (Adjust node-version as needed)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Set the Node.js version you are using

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the project
      - name: Build the project
        run: npm run build
        env:
          NODE_ENV: production

      # Deploy to GitHub Pages using peaceiris/actions-gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically provides this token
          publish_dir: ./dist  # The directory where the built files are located
          force_orphan: true  # Creates a new orphan branch for the deployment
