
name: Build and Test

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out repository with submodules and history
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      # Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      # Install dependencies with CI flag
      - name: Install dependencies
        run: npm ci
        
      # Update browserslist database
      - name: Update browserslist database
        run: npx update-browserslist-db@latest
        
      # Run security audit
      - name: Security audit
        run: npm audit --production

      # Build the project
      - name: Build the project
        run: npm run build
        env:
          NODE_ENV: production
          # Add any other environment variables your build might need
          
      # Test the build artifacts
      - name: Test build
        run: |
          if [ ! -d "./dist" ]; then
            echo "Build failed - dist directory not created"
            exit 1
          fi
          if [ ! -f "./dist/index.html" ]; then
            echo "Build failed - index.html not created"
            exit 1
          fi
